# Generated by Django 4.2.2 on 2023-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('gen', 'General'), ('hel', 'Health'), ('eco', 'Economics')], default='gen', max_length=20),
        ),
    ]
