# Generated by Django 4.2.2 on 2023-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_permissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='permissions',
            field=models.CharField(choices=[('add_article', 'Add article'), ('edit_article', 'Edit article'), ('delete_article', 'Delete article')], max_length=20),
        ),
    ]
