# Generated by Django 4.2.2 on 2023-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newsapp', '0005_alter_permissionrequest_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='permissions',
            field=models.ManyToManyField(choices=[('add_article', 'Add article'), ('edit_article', 'Edit article'), ('delete_article', 'Delete article')], to='auth.permission'),
        ),
    ]
