# Generated by Django 4.2.2 on 2023-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_permissionrequest_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='permissions',
            field=models.ManyToManyField(choices=[('add_article', 'Add article'), ('edit_article', 'Edit article'), ('delete_article', 'Delete article')], to='newsapp.staffpermission'),
        ),
    ]
