# Generated by Django 4.2.2 on 2023-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_staffpermission_alter_permissionrequest_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='permissions',
            field=models.ManyToManyField(to='newsapp.staffpermission'),
        ),
    ]
