# Generated by Django 4.2.2 on 2023-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_permissionrequest_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpermission',
            name='description',
        ),
        migrations.AlterField(
            model_name='staffpermission',
            name='name',
            field=models.CharField(choices=[('add_article', 'Add article'), ('edit_article', 'Edit article'), ('delete_article', 'Delete article')], max_length=50),
        ),
    ]
