# Generated by Django 4.2.2 on 2023-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_remove_staffpermission_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='StaffPermission',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='permissions',
            field=models.CharField(choices=[('add_article', 'Add article'), ('edit_article', 'Edit article'), ('delete_article', 'Delete article')], default='None', max_length=20),
        ),
    ]
