# Generated by Django 4.2.2 on 2023-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newsapp', '0011_custompermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
