# Generated by Django 4.2.2 on 2023-06-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_delete_custompermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('edit_title', 'Can edit article titles')]},
        ),
    ]
