# Generated by Django 4.2.2 on 2023-06-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0016_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('world', 'World'), ('nation', 'Nation'), ('business', 'Business'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('science', 'Science'), ('health', 'Health')], default='gen', max_length=20),
        ),
    ]
